<?php
/**
 * @file
 * pdfcrowd_textarea.module
 */

/**
 * Implements hook_menu().
 */
function pdfcrowd_textarea_menu() {
  $items['admin/config/services/pdfcrowd/textarea'] = array(
    'title' => 'PDF Crowd textarea',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('pdfcrowd_textarea_form'),
    'access arguments' => array('administer site configuration'),
    'type' => MENU_LOCAL_TASK,
  );
  return $items;
}

/**
 * This form allows you to build PDF document based on custom HTML code.
 */
function pdfcrowd_textarea_form($form, &$form_state) {
  $form['html'] = array(
    '#type' => 'textarea',
    '#title' => t('HTML code'),
    '#description' => t('Place your HTML code here.'),
    '#required' => TRUE,
    '#rows' => 20,
  );
  $form['settings'] = array(
    '#type' => 'fieldset',
    '#title' => t('Render settings'),
    '#collapsible' => TRUE,
    '#collapsed' => TRUE,
  );
  $form['settings']['document_size'] = array(
    '#type' => 'select',
    '#title' => t('Document type'),
    '#options' => array(
      'a4_portrait' => t('A4 Portrait'),
      'a4_landscape' => t('A4 Landscape'),
    ),
  );
  $form['actions'] = array('#type' => 'actions');
  $form['actions']['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Submit'),
  );
  return $form;
}

/**
 * Submit handler for textarea form.
 */
function pdfcrowd_textarea_form_submit($form, &$form_state) {

  $form_state['rebuild'] = TRUE;

  // Prepare dates in different formats.
  $last_modified = gmdate(DATE_RFC1123, REQUEST_TIME);
  $etag = '"' . md5($last_modified) . '"';

  // Load library.
  $pdf = pdfcrowd_load_library();

  // Set default page size.
  switch ($form_state['values']['document_size']) {
    case 'a4_landscape':
      $pdf->setPageHeight("210mm");
      $pdf->setPageWidth("298mm");
      break;
    case 'a4_portrait':
    default:
      // A4 Portrait by default.
      $pdf->setPageHeight("298mm");
      $pdf->setPageWidth("210mm");
      break;
  }

  // Render document.
  $output = $pdf->convertHtml($form_state['values']['html']);

  // Prepare headers.
  $headers = array(
    'Content-type' => 'Content-Type: application/pdf; charset=utf-8',
    'Last-modified' => $last_modified,
    'Etag' => $etag,
    'Expires' => $last_modified,
    'X-Robots-Tag' => 'noindex, follow',
    'Pragma' => 'no-cache',
    'Cache-Control' => 'private',
    'Content-Transfer-Encoding' => 'binary',
    'Content-Length' => strlen($output),
    'Content-Disposition' => 'attachment; filename="pdfcrowd_textarea.pdf"',
  );

  // Set headers.
  foreach ($headers as $name => $value) {
    drupal_add_http_header($name, $value);
  }
  drupal_send_headers();

  // Print output.
  print $output;

  // Exit Drupal bootstrap.
  drupal_exit();
}
